### ISSUE TITLE
[FEATURE] - allow passing compressor flags to xz and other compressors as tar

### ISSUE THREAD

**Issue by braindevices** [Edrusb/DAR#23]
nowadays use multiple core for compressor is very important, we want to be able to control how many cores the compressor should use. in tar we can use `XZ_OPT="-9e --threads=8"` to set the thread number and give more control about the compressor. This is very useful. Now dar is about 4x slower than tar with XZ_OPT.
here is dar:
```
1246.68user 86.37system 22:32.89elapsed 98%CPU (0avgtext+0avgdata 702080maxresident)k
7040096inputs+1360024outputs (0major+82465076minor)pagefaults 0swaps
```
here is tar:
```
2676.54user 9.83system 5:27.02elapsed 821%CPU (0avgtext+0avgdata 9383300maxresident)k
7039720inputs+1045000outputs (0major+2510112minor)pagefaults 0swaps
```

**Comment by Edrusb** [comment]
Hi, this feature is implemented and will be available with release 2.7.0, you can already test code on master and read the man page about -G and -z options.

**Comment by Edrusb** [comment]
By the way, you should compare time for the same feature sets, sparse file, extended attributes, filesystem attributes, atime, file checksum, metadata redundancy. Tar does not protect the backed up data against corruption, thing dar does and which has a certain CPU cost, though the overall time execution is not that big when comparing with same number of processor used.

Cheers

**Comment by braindevices** [comment]
Thanks I will look into the new version. @Edrusb It is really not about the metadata, just the XZ_OPT, remove the XZ_OPT the tar has similar speed as dar. Is it possible to enable XZ_OPT, so we can easily control all xz tools with single setting? At first glance it does not seem to be very difficult since the xz lib itself support it already.

**Comment by Edrusb** [comment]
Compression with tar is equivalent to piping tar output to the compressor commands (gzip, bzip2, xz, ...) :
`tar -cf - | xz -e9 --thread 8 - > backup.txz`
or
`xz --decompress --thread 8 - < backup.txz | tar -xf - `
A small shell script wrapping xz and tar and using the environment variable XZ_OPT you mentionned can do that easily, there is nothing much complicated effectively in doing that.

The difference with dar is that it performs compression per file (for better backup robustness: a given corruption does not avoid you to restore all files following it, but just the file where this corruption occurred). Starting with the future 2.7.0 version, dar will also add compression per block (and still per file) as does xz command line tool, to allow multi-threading.

I found more interesting to re-implement the multi-threading withing libdar independently from the compression algorithm for it can be leveraged by all compression algorithms libdar supports: gzip, bzip2, lz4, lzo2, zstd and xz algorithms. This way performance is very good for all compression algorithms. However, due to the per file compression choice if implementation, small files that cannot lead to many blocks and thus many threads, while they still get better compression performance than single threaded approach, may not use all assigned compression threads. This is the drawback of robustness.

By the way, nothing forbids you to pipe dar output to xz as shown above with tar, you will have with current version the same performance speed as you mentioned with tar, but you will have the same drawbacks as what you get with tar: a fragile backup.

Also note that by default tar uses the default compression ratio (6 for gzip), while dar uses 9 for all thing you can change with -z option. This gives very different execution time!!!

Anyway, thank you for your feedback!

**Comment by Edrusb** [comment]
closing issue with release 2.7.0 cleanup
