### ISSUE TITLE
Сan't build 2.7.7 with libthreadar 1.4.0 and clang 10.0.1

### ISSUE THREAD

**Issue by igorzigorz** [Edrusb/DAR#38]
Can't build in FreeBSD 12.3 with clang version 10.0.1 and 11.0.1
But no error with FreeBSD 13.1 and clang version 13.0.0.
I want to update the dar port. This requires no errors in versions 12.3 and 13.1

In file included from parallel_tronconneuse.cpp:28:
In file included from ./parallel_tronconneuse.hpp:39:
In file included from /usr/include/c++/v1/string:504:
In file included from /usr/include/c++/v1/string_view:175:
In file included from /usr/include/c++/v1/__string:57:
In file included from /usr/include/c++/v1/algorithm:643:
/usr/include/c++/v1/memory:3556:7: error: exception specification of overriding function is more lax than base version
class __shared_ptr_emplace
      ^
/usr/include/c++/v1/memory:4402:26: note: in instantiation of template class 'std::__1::__shared_ptr_emplace<libthreadar::barrier, std::__1::allocator<libthreadar::barrier> >' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
parallel_tronconneuse.cpp:102:15: note: in instantiation of function template specialization 'std::__1::make_shared<libthreadar::barrier, unsigned long>' requested here
            waiter = make_shared<barrier>(num_workers + 2); // +1 for crypto_reade thread, +1 this thread
                     ^
/usr/include/c++/v1/memory:3465:13: note: overridden virtual function is here
    virtual ~__shared_weak_count();
            ^
1 error generated.
*** [parallel_tronconneuse.lo] Error code 1

**Comment by Edrusb** [comment]
this seems to be a bug with clang 10.0.1. which canot accept class having a destructor able to throw exception (here libthreadar::barrier)

A workaround at libthreadar level using default destructor specification fixes the issue with clang 10.0.1 but creates an expected problem with GCC 4:10.2.1-1/Debian (if an exception is raised from the destructor: this triggers the terminate function, which is the expected behavior in that context, but not the needed behavior, thus the exception specification of the destructor is required.
 
looking forward to find a solution at dar level...

**Comment by Edrusb** [comment]
Well, I have modified dar code to workaround this problem, though the change is very small and is the only one since recent 2.7.7 release. Thus I will not create 2.7.8 just for that. However you have 2.7.8.RC1 (release candidate 1) available on github and at https://dar.edrusb.org/dar.linux.free.fr/Interim_releases/ that compiles and works under FreeBSD 12 with clang 10.0.1

**Comment by igorzigorz** [comment]
There is no problem now.
