### ISSUE TITLE
Bug in elastic.cpp

### ISSUE THREAD

**Issue by Sviat89** [Edrusb/DAR#40]
`elastic::elastic(const unsigned char *buffer, U_32 size, elastic_direction dir, const archive_version & reading_ver)`
When `dir == elastic_backward`, all conditions like `pos < size` are wrong. It should be `pos >= 0` maybe

**Comment by Edrusb** [comment]
yes, but no in fact!  :)

Because the `pos` variable is _unsigned_. Thus, when reading backward if it get out of bound (decreased from a previous value of zero) its value wraps around and get the highest possible value for this (unsigned) integer type. Thus the `pos < size` control code stays pertinent also in backward direction !

**Comment by Sviat89** [comment]
Yes, my fault

**Comment by Edrusb** [comment]
no problem, I have added some comment in the code because this is not obvious at all: at first I thought you were right, that there was a bug. Thanks for your feedback anyway, and thanks to read the code! :)
