### ISSUE TITLE
cp: illegal option -- d

### ISSUE THREAD

**Issue by ryandesign** [Edrusb/DAR#54]
I noticed this output when installing dar 2.7.11 on macOS 12:

```
make[4]: Entering directory `/opt/local/var/macports/build/_Volumes_Shared_macports-ports_archivers_dar/dar/work/dar-2.7.11/doc'
'./portable_cp' html /opt/local/var/macports/build/_Volumes_Shared_macports-ports_archivers_dar/dar/work/destroot/opt/local/share/dar
cp: illegal option -- d
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file ... target_directory
```

The installation still proceeded and exited with a successful status code.

**Comment by Edrusb** [comment]
Yes, if you read the doc/portable_cp script (found in source code), you'll see that it tries different options to the cp command and depending on the result (its exit status) tries another combination

if this script failed, it would first exit with non zero status code and would also display something like

"Impossible to create .... or .... in order to determine capabilities of the 'cp' command"

So there is no issue here, though I will redirect the two cp tentative outputs to /dev/null for this message to not show.

Thanks for feedback

**Comment by Edrusb** [comment]
closing report with release 2.7.12 that integrates this fix
